spring:
  application:
    name: ms-catalogo-service
  profiles:
    active: development
  config:
    import: optional:configserver:http://root:123456@localhost:9090/

  datasource:
    url: jdbc:mysql://localhost:3306/ms-catalogo
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver